<a href="https://colab.research.google.com/github/Amit-Padye/Pytorch-/blob/main/Auto_grad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch, torchvision

In [3]:

model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


  0%|          | 0.00/44.7M [00:00<?, ?B/s]

In [4]:
data

tensor([[[[0.3817, 0.0228, 0.9325,  ..., 0.8250, 0.6594, 0.0185],
          [0.2364, 0.0743, 0.2260,  ..., 0.3389, 0.9315, 0.9411],
          [0.2750, 0.3503, 0.5444,  ..., 0.1172, 0.6386, 0.1905],
          ...,
          [0.4556, 0.4401, 0.9792,  ..., 0.7586, 0.9651, 0.8448],
          [0.6344, 0.8621, 0.5860,  ..., 0.4563, 0.2435, 0.8043],
          [0.2600, 0.6780, 0.8343,  ..., 0.6575, 0.3798, 0.7388]],

         [[0.4997, 0.3611, 0.4205,  ..., 0.4458, 0.3066, 0.1079],
          [0.0319, 0.3365, 0.9202,  ..., 0.0989, 0.4530, 0.5643],
          [0.2579, 0.9922, 0.3478,  ..., 0.5668, 0.3268, 0.0837],
          ...,
          [0.2066, 0.8446, 0.2210,  ..., 0.5179, 0.9658, 0.3530],
          [0.3807, 0.9634, 0.9288,  ..., 0.4418, 0.9193, 0.8825],
          [0.2385, 0.5881, 0.2699,  ..., 0.4374, 0.8486, 0.3505]],

         [[0.4818, 0.1704, 0.4038,  ..., 0.6527, 0.6908, 0.3570],
          [0.1395, 0.8256, 0.9924,  ..., 0.4743, 0.0638, 0.5095],
          [0.1901, 0.3052, 0.8544,  ..., 0

In [5]:
labels

tensor([[9.9491e-01, 2.7120e-01, 6.1022e-01, 5.9924e-01, 2.8215e-01, 2.2507e-01,
         6.8383e-01, 7.6006e-01, 1.4318e-01, 8.9480e-01, 3.9497e-02, 5.3770e-01,
         5.5884e-01, 1.5290e-01, 8.8386e-01, 1.9433e-01, 5.9557e-01, 8.2181e-01,
         9.5348e-01, 6.5905e-01, 4.8634e-01, 9.5765e-01, 2.3658e-01, 9.8695e-01,
         9.7410e-01, 5.9077e-01, 7.6933e-01, 4.7997e-02, 3.2074e-01, 9.1713e-01,
         8.1331e-01, 5.8764e-02, 8.9768e-01, 8.9054e-02, 4.1638e-01, 5.8787e-01,
         7.6411e-01, 5.9865e-01, 6.1981e-01, 3.6120e-01, 4.7059e-01, 7.9591e-01,
         2.3459e-01, 1.9039e-01, 8.2985e-01, 5.6005e-01, 1.5671e-01, 1.4197e-01,
         1.0150e-01, 2.9716e-01, 5.5070e-01, 7.7853e-02, 7.4603e-01, 4.6544e-01,
         9.3030e-01, 1.5451e-01, 2.2823e-01, 1.5447e-01, 8.4179e-01, 6.9737e-01,
         7.6228e-01, 1.6129e-04, 6.8038e-01, 9.4416e-02, 1.0684e-01, 2.1001e-02,
         2.5663e-01, 9.9244e-01, 5.9172e-01, 8.4020e-02, 6.6109e-02, 7.9227e-01,
         8.4000e-01, 7.5991e

In [6]:
prediction = model(data) # forward pass

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)


In [7]:
loss = (prediction - labels).sum()
loss.backward() # backward pass

In [8]:
loss

tensor(-488.5651, grad_fn=<SumBackward0>)

In [9]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [10]:
optim.step() #gradient descent

In [11]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [12]:
Q = 3*a**3 - b**2

In [13]:
Q

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [14]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [15]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])
