<a href="https://colab.research.google.com/github/Amit-Padye/Pytorch-/blob/main/Pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [19]:


if torch.cuda.is_available():
  device = torch.device("cuda")
else:
  device = torch.device("cpu")

In [2]:
data=[[1,2],[3,5]]
x=torch.tensor(data)

#Creating Tensor

In [3]:
x

tensor([[1, 2],
        [3, 5]])

In [4]:
type(x)

torch.Tensor

In [5]:
x=np.array([[1,2],[2,3]])

In [6]:
t=torch.tensor(x)

In [7]:
t

tensor([[1, 2],
        [2, 3]])

In [8]:
t.shape

torch.Size([2, 2])

In [9]:
x_ones = torch.ones_like(t) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [10]:

x_rand = torch.rand_like(t, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.3933, 0.2873],
        [0.0444, 0.4998]]) 



###With random or constant values:

In [11]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5070, 0.9406, 0.5914],
        [0.9980, 0.1036, 0.0324]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
#with random value
random_tensor=torch.rand((2,3))
random_tensor

tensor([[0.9396, 0.6680, 0.0335],
        [0.8299, 0.9741, 0.9392]])

In [13]:
#tensor with value 1
one_tensor=torch.ones((2,3))
one_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
zero_tensor=torch.zeros((2,3,3))
zero_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

###Tensor Attributes

In [15]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [16]:
tensor=torch.rand(2,3)
tensor.shape

torch.Size([2, 3])

In [17]:
tensor.dtype

torch.float32

In [22]:
tensor.device

device(type='cuda', index=0)

###Tensor Operations

In [28]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [21]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [24]:
tensor=torch.ones(2,3)
tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [27]:
tensor[:,1:]

tensor([[1., 1.],
        [1., 1.]])

###Joining Tensor

In [31]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [32]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


###Multiplying tensors

In [36]:
tensor1=2*torch.ones((3,3))
print(tensor1)
tensor2=3*torch.ones((3,3))
print(tensor2)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


###Element wise multiplication

In [38]:
tensor1*tensor2

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])

In [40]:
tensor1.mul(tensor2)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])

In [41]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[4., 4., 4.],
        [4., 4., 4.]]) 

tensor * tensor 
 tensor([[4., 4., 4.],
        [4., 4., 4.]])


###This computes the matrix multiplication between two tensors

In [45]:
tensor=2*torch.ones((2,3))
print(tensor)
print(tensor.shape)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
torch.Size([2, 3])


In [46]:
print(tensor.T)
print(tensor.T.shape)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
torch.Size([3, 2])


In [48]:
tensor.matmul(tensor.T)

tensor([[12., 12.],
        [12., 12.]])

In [50]:
tensor @ tensor.T

tensor([[12., 12.],
        [12., 12.]])

In [51]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[12., 12.],
        [12., 12.]]) 

tensor @ tensor.T 
 tensor([[12., 12.],
        [12., 12.]])


###Tensor to NumPy

In [52]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


###NumPy array to Tensor

In [53]:
n = np.ones(5)
t = torch.from_numpy(n)

In [54]:
n

array([1., 1., 1., 1., 1.])

In [55]:
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)